### ISSUE TITLE
'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by zbynekdrlik** [agateblue/django-dynamic-preferences#163]
I am trying add new sections to dynamic_preferences_registry.py but after changes django admin get this error:
'NoneType' object has no attribute 'name'

My registry
```
# blog/dynamic_preferences_registry.py

from dynamic_preferences.types import BooleanPreference, StringPreference, LongStringPreference
from dynamic_preferences.preferences import Section
from dynamic_preferences.registries import global_preferences_registry
from dynamic_preferences.users.registries import user_preferences_registry

# we create some section objects to link related preferences together

sec_admin = Section('ft5000admin')
sec_servis = Section('ft5000servis')
sec_view = Section('ekasa')

# # We start with a global preference
@global_preferences_registry.register
class BlHlavicka(LongStringPreference):
     section = sec_servis
     name = 'bl_hlavicka'
     default = 'FT 5000\nTestovacia hlavicka'
     required = False

@global_preferences_registry.register
class MaintenanceMode(BooleanPreference):
    #section = general
    name = 'maintenance_mode'
    default = False
```

**Comment by EliotBerriot** [comment]
Can you please share the full stack track for your error?

**Comment by zbynekdrlik** [comment]
It is already solved. I need to cleanup my registry after changes. If I changed section on already created preference it went to this error

**Comment by gonzaloamadio** [comment]
How have you solved this error?

**Comment by salian** [comment]
After editing the default sections and adding new sections to dynamic_preferences_registry.py, django admin shows the error: **'NoneType' object has no attribute 'name'**

Here is the stack
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/

Django Version: 2.1.7
Python Version: 3.6.1
Installed Applications:
['grappelli',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'corsheaders',
 'fontawesome',
 'taggit',
 'taggit_autosuggest',
 'taggit_serializer',
 'colorfield',
 'myapp',
 'dynamic_preferences']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  156.                 response = self.process_exception_by_middleware(e, request)

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  154.                 response = response.render()

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/django/template/response.py" in render
  106.             self.content = self.rendered_content

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/django/template/response.py" in rendered_content
  83.         content = template.render(context, self._request)

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/django/template/base.py" in render
  169.                 with context.bind_template(self):

File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py" in __enter__
  82.             return next(self.gen)

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/django/template/context.py" in bind_template
  246.             updates.update(processor(self.request))

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/dynamic_preferences/processors.py" in global_preferences
  10.     return {'global_preferences': manager.all()}

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/dynamic_preferences/managers.py" in all
  187.             return self.load_from_db()

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/dynamic_preferences/managers.py" in load_from_db
  205.         db_prefs = {p.preference.identifier(): p for p in self.queryset}

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/dynamic_preferences/managers.py" in <dictcomp>
  205.         db_prefs = {p.preference.identifier(): p for p in self.queryset}

File "/Users/myuser/mypath/myproject-api-venv/lib/python3.6/site-packages/dynamic_preferences/preferences.py" in identifier
  93.         if not self.section.name:

Exception Type: AttributeError at /admin/
Exception Value: 'NoneType' object has no attribute 'name'
```

After playing around a bit I realised this was because I edited the existing "MaintenanceMode" preference in dynamic_preferences_registry.py, adding a "section" to it.

```
@global_preferences_registry.register
class MaintenanceMode(BooleanPreference):
    name = 'maintenance_mode'
    default = False
```

Upon reverting that and applying `manage.py checkpreferences` for good measure, the error went away. 

This is definitely a confusing way to do things.

**Comment by zbynekdrlik** [comment]
`(venv) ft5000@localhost:~/devel/200$ python3 manage.py checkpreferences 
/home/ft5000/devel/200/venv/lib/python3.6/site-packages/dynamic_preferences/registries.py:136: UserWarning: Creating a fallback preference with section "None" and name "dic".This means you have preferences in your database that don't match any registered preference. If you want to delete these entries, please refer to the documentation: https://django-dynamic-preferences.readthedocs.io/en/latest/lifecycle.html
  warnings.warn(message.format(section_name, pref_name))
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/dynamic_preferences/management/commands/checkpreferences.py", line 37, in handle
    manager.all()
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/dynamic_preferences/managers.py", line 199, in all
    a.update(self.load_from_db(cache=True))
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/dynamic_preferences/managers.py", line 205, in load_from_db
    db_prefs = {p.preference.identifier(): p for p in self.queryset}
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/dynamic_preferences/managers.py", line 205, in <dictcomp>
    db_prefs = {p.preference.identifier(): p for p in self.queryset}
  File "/home/ft5000/devel/200/venv/lib/python3.6/site-packages/dynamic_preferences/preferences.py", line 93, in identifier
    if not self.section.name:
AttributeError: 'NoneType' object has no attribute 'name'
(venv) ft5000@localhost:~/devel/200$ 
`

**Comment by zbynekdrlik** [comment]
The problem still persist, but now I can't cleanup all settings.

**Comment by MishaGubsky** [comment]
I solved the problem by removing record without "section" manually into db. This is a fast way, but not a perfect one.

**Comment by zbynekdrlik** [comment]
+1
